### ISSUE TITLE
Parsing EDMX file in .NET Core 3 throws exception

### ISSUE THREAD

**Issue by robertmclaws** [dotnet/ef6#1230]
I am building a replacement for the EF6 T4 templates, because T4 is a dead technology and the T4 templates that ship with EF6 are difficult to maintain and outdated. It uses the same EdmItemCollection.Create method that the T4 templates use to parse the EDMX file's CSDL into actionable entities.

I have my generator tested working in various situations (regular libraries, unit tests, and so forth). But I'm trying to run it inside a `dotnet script` .csx file, and I'm running into the following exception:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'System.Data.Entity.Internal.AppConfig' threw an exception. ---> System.IO.FileLoadException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621) ---> System.IO.FileLoadException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.AppDomain.InvokeResolveEvent(ResolveEventHandler eventHandler, RuntimeAssembly assembly, String name)
   --- End of inner exception stack trace ---
   at System.Data.Entity.Internal.AppConfig..ctor()
   at System.Data.Entity.Internal.AppConfig..cctor()
   --- End of inner exception stack trace ---
   at System.Data.Entity.Infrastructure.DependencyResolution.InternalConfiguration..ctor(ResolverChain appConfigChain, ResolverChain normalResolverChain, RootDependencyResolver rootResolver, AppConfigDependencyResolver appConfigResolver, Func`1 dispatchers)
   at System.Data.Entity.DbConfiguration..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Data.Entity.Utilities.TypeExtensions.CreateInstance[T](Type type, Func`2 exceptionFactory)
   at System.Data.Entity.Infrastructure.DependencyResolution.DbConfigurationManager.<.ctor>b__10_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Data.Entity.Infrastructure.DependencyResolution.DbConfigurationManager.GetConfiguration()
   at System.Data.Entity.Core.SchemaObjectModel.SchemaElement..ctor(SchemaElement parentElement, IDbDependencyResolver resolver)
   at System.Data.Entity.Core.SchemaObjectModel.Schema..ctor(SchemaManager schemaManager)
   at System.Data.Entity.Core.SchemaObjectModel.SchemaManager.ParseAndValidate(IEnumerable`1 xmlReaders, IEnumerable`1 sourceFilePaths, SchemaDataModelOption dataModel, AttributeValueNotification providerNotification, AttributeValueNotification providerManifestTokenNotification, ProviderManifestNeeded providerManifestNeeded, IList`1& schemaCollection)
   at System.Data.Entity.Core.SchemaObjectModel.SchemaManager.ParseAndValidate(IEnumerable`1 xmlReaders, IEnumerable`1 sourceFilePaths, SchemaDataModelOption dataModel, DbProviderManifest providerManifest, IList`1& schemaCollection)
   at System.Data.Entity.Core.Metadata.Edm.EdmItemCollection.LoadItems(IEnumerable`1 xmlReaders, IEnumerable`1 sourceFilePaths, SchemaDataModelOption dataModelOption, DbProviderManifest providerManifest, ItemCollection itemCollection, Boolean throwOnError)
   at System.Data.Entity.Core.Metadata.Edm.EdmItemCollection..ctor(IEnumerable`1 xmlReaders, ReadOnlyCollection`1 filePaths, IList`1& errors)
   at System.Data.Entity.Core.Metadata.Edm.EdmItemCollection.Create(IEnumerable`1 xmlReaders, ReadOnlyCollection`1 filePaths, IList`1& errors)
   at CloudNimble.EasyAF.CodeGen.EdmxLoader.Load()
   at Submission#0.<<Initialize>>d__0.MoveNext() in D:\Scratch\EasyAF\CloudNimble.Test\cloudnimble.test.core\easyaf.core.csx:line 30
--- End of stack trace from previous location where exception was thrown ---
   at Dotnet.Script.Core.ScriptRunner.Execute[TReturn](String dllPath, IEnumerable`1 commandLineArgs) in C:\Users\appveyor\AppData\Local\Temp\tmp382F\Dotnet.Script.Core\ScriptRunner.cs:line 58
```

I'm handling the fact that this shouldn't be happening in `dotnet script` in their repo. HOWEVER
this line doesn't appear to be necessary when you're just parsing a text file: https://github.com/aspnet/EntityFramework6/blob/release/6.4/src/EntityFramework/Core/SchemaObjectModel/SchemaElement.cs#L267

Feels like there should be a way to get down this path without needing to depend on the Configuration system. Maybe open up some of these classes so we don't have to go through the static `EdmItemCollection.Create()` method?

### Further technical details
EF version:  6.3.0-preview9-19423-04
Database Provider: N/A
Operating system: Windows 10
IDE: VS 2019 16.3 Preview 3.

**Comment by ajcvickers** [comment]
@robertmclaws We're having difficulty following exactly what it is that you are trying to achieve. Could you maybe post code and show where it's not doing what you expect?

**Comment by robertmclaws** [comment]
OK, I've posted a sample project here: https://github.com/robertmclaws/EDMXParsingSample

I tried to keep the EdmxLoader as simple as possible. It should feel familiar, as it shares a similar structure to [the EdmMetadataLoader in the .ttinclude file](https://github.com/aspnet/EntityFramework6/blob/release/6.4/src/EFTools/EntityDesign/TextTemplates/Includes/EF6.Utility.CS.ttinclude#L1490-L1602).

As I mentioned, the exception itself is being thrown because `dotnet-script` is not loading the proper `System.Configuration` assembly execute [this line of code](https://github.com/aspnet/EntityFramework6/blob/release/6.4/src/EntityFramework/Core/SchemaObjectModel/SchemaElement.cs#L267). That part is not your problem, so don't worry about fixing it.

However, the fact that assembly wasn't able to load exposed a design flow in the code path. It should not be necessary to load *anything* from a web.config or app.config file just to parse the CSDL into objects, just as Newtonsoft.Json.JsonConvert() does not need access to the web.config to function. If you're making a database connection to do actual work, absolutely. But that's not the only reason why you'd materialize an `EdmItemCollection`, yet EF's architecture assumes that it is.

It would be great if the codepath could be adjusted not to require a call to `DbConfigurationManager.GetConfiguration()`.

Thanks!

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
