### ISSUE TITLE
ClrEntityType Hash calculating over ASCII encoding causes exception if national names of entity types used

### ISSUE THREAD

**Issue by SocSoftSpb** [dotnet/ef6#1477]
Exception message: System.ArgumentException: 'Duplicate type name within an assembly.'
Stack trace:  
```
at System.Reflection.Emit.ModuleBuilder.CheckTypeNameConflict(String strTypeName, Type enclosingType)
   at System.Reflection.Emit.AssemblyBuilderData.CheckTypeNameConflict(String strTypeName, TypeBuilder enclosingType)
   at System.Reflection.Emit.TypeBuilder.Init(String fullname, TypeAttributes attr, Type parent, Type[] interfaces, ModuleBuilder module, PackingSize iPackingSize, Int32 iTypeSize, TypeBuilder enclosingType)
   at System.Reflection.Emit.ModuleBuilder.DefineType(String name, TypeAttributes attr, Type parent, Type[] interfaces)
   at System.Data.Entity.Core.Objects.Internal.EntityProxyFactory.ProxyTypeBuilder.get_TypeBuilder() 
```

### Steps to reproduce
Add to model two types with identical properties and National (Unicode) type names with identical first 20 characters and identical length.

Root of problem:
code in ClrEntityType.BuildEntityTypeHash():
```c#
var hash = sha256HashAlgorithm.ComputeHash(Encoding.ASCII.GetBytes(BuildEntityTypeDescription()));
```

Encoding.ASCII translate national letters to '?' and two types have a identical hash.

Fix please with using Encoding.Unicode.
Same issue possible also in ModelHashCalculator.

### Further technical details
EF version: 6.x
Database Provider: EntityFramework.SqlServer

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
