### ISSUE TITLE
DbContext with open SQL connection passed into DbMigrator seems not to be used

### ISSUE THREAD

**Issue by benhxy** [dotnet/ef6#1548]
## Related code:
https://github.com/dotnet/ef6/blob/2274eb9ce8deef56e3ccf2e3a29efb10339785d9/src/EntityFramework/Migrations/DbMigrator.cs#L616

## Background
* We are using EF6 with Azure SQL and are trying to migrate to AAD/MSI token based authentication.
* I did following code changes:
    * Create a DbContext in which a AAD-token-based SQL connection is already opened.
    * Pass the DbContext into DbMigrator so it can migrate code-first migrations.
* This is what I did (with EF 6.4.0): 
```
var config = new TConfig
{
    ContextType = typeof(TContext),
    AutomaticMigrationsEnabled = true,
    AutomaticMigrationDataLossAllowed = true
};
var migrator = new DbMigrator(config, migrationContext);
var migrationName = migrator.GetLocalMigrations().Last();
migrator.Configuration.AutomaticMigrationsEnabled = false;
migrator.Update(migrationName);
```
 
## Error
However I got this error. It seems that during DbMigrate.Upgrate(), the DbContext is trying to lazily initialize another DbMigrator. But since the existing DbContext is not passed into the constructor, eventually SQL connection failed (because connection string does not contain any credential).
```
   at System.Data.SqlClient.SqlConnection.PermissionDemand()
   at System.Data.SqlClient.SqlConnectionFactory.PermissionDemand(DbConnection outerConnection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.IGAELM.Common.ConnectionManager.Sql.BaseDbContext.GetSqlConnection(ISqlSettings sqlSettings, ITracer tracer) in c:\One\AD\IGA\Store\src\Dev\Common\ConnectionManager\Sql\BaseDbContext.cs:line 401
   at Microsoft.IGAELM.Common.ConnectionManager.Sql.BaseDbContext..ctor(ISqlSettings sqlSettings, ITracer tracer, IRequestContext requestContext) in c:\One\AD\IGA\Store\src\Dev\Common\ConnectionManager\Sql\BaseDbContext.cs:line 76
   at Microsoft.IGAELM.Common.ConnectionManager.SqlMigration.ECMigrationContext..ctor() in c:\One\AD\IGA\Store\src\Dev\Common\ConnectionManager\SqlMigration\ECMigrationContext.cs:line 26

--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Data.Entity.Infrastructure.DbContextInfo.CreateInstance()
   at System.Data.Entity.Infrastructure.DbContextInfo..ctor(Type contextType, DbProviderInfo modelProviderInfo, AppConfig config, DbConnectionInfo connectionInfo, Func`1 resolver)
   at System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationsConfiguration configuration, DbContext usersContext, DatabaseExistenceState existenceState, Boolean calledByCreateDatabase)
   at System.Data.Entity.MigrateDatabaseToLatestVersion`2.InitializeDatabase(TContext context)
   at System.Data.Entity.Internal.InternalContext.<>c__DisplayClass66_0`1.<CreateInitializationAction>b__0()
   at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   at System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   at System.Data.Entity.Internal.LazyInternalContext.<>c.<InitializeDatabase>b__58_0(InternalContext c)
   at System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabase()
   at System.Data.Entity.Internal.InternalContext.Initialize()
   at System.Data.Entity.Internal.LazyInternalContext.get_ObjectContext()
   at System.Data.Entity.Internal.InternalContext.DetectChanges(Boolean force)
   at System.Data.Entity.Internal.InternalContext.GetStateEntries(Func`2 predicate)
   at System.Data.Entity.Internal.InternalContext.GetStateEntries()
   at System.Data.Entity.Infrastructure.DbChangeTracker.Entries()
   at System.Data.Entity.DbContext.GetValidationErrors()
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   at System.Data.Entity.DbContext.SaveChanges()
   at System.Data.Entity.Migrations.DbMigrator.SeedDatabase()
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
   at System.Data.Entity.Migrations.DbMigrator.<>c__DisplayClass42_0.<Update>b__0()
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at Microsoft.IGAELM.Common.ConnectionManager.SqlMigration.Migration.Migrate[T,TConfig](T migrationContext, ITracer tracer) in c:\One\AD\IGA\Store\src\Dev\Common\ConnectionManager\SqlMigration\Migration.cs:line 181
   at Microsoft.IGAELM.Common.ConnectionManager.SqlMigration.Migration.ApplyDatabaseMigration(String database, ITracer tracer) in c:\One\AD\IGA\Store\src\Dev\Common\ConnectionManager\SqlMigration\Migration.cs:line 119
```

**Comment by ajcvickers** [comment]
@benhxy From the stack trace it looks like the `MigrateDatabaseToLatestVersion` database initializer is running. Since I was able to dig into your code a bit (thanks!) I expect this is because `ECMigrationContext` is configuring the initializer:

```C#
this.DatabaseInitializer = new MigrateDatabaseToLatestVersion<ECMigrationContext, Migrations.EC.Configuration>();
```

Now the base context also does this:

```C#
Database.SetInitializer<BaseDbContext>(null);
```
but that won't override what the inherited context is doing since initializers are not inherited. So you need to make sure that somewhere you configure:

```C#
Database.SetInitializer<MigrateDatabaseToLatestVersion>(null);
```

One trick I have seen for this is to make the base context generic on the actual context type. Something like:

```C#
public class BaseContext<TContext> : DbContext
    where TContext : DbContext
{
    protected BaseContext()
    {
        Database.SetInitializer<TContext>(null);
    }
}
```

**Comment by benhxy** [comment]
Ah I see. Let me try that solution. Thank you so much!

**Comment by benhxy** [comment]
Great! It worked. So it turns out I should just set every subclass's initializer to null. It seesm like Migration classes will take care of the initialization without the initializer. Thank you a lot.
