### ISSUE TITLE
NullReferenceException when invoking DbContext.SaveChanges()

### ISSUE THREAD

**Issue by vlardn** [dotnet/ef6#1577]
Time to time (a few times per week) our high load production system getting NullReferenceException when invoking DbContext.SaveChanges():

```
Exception message:
Stack trace:

System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at System.Data.Entity.Infrastructure.CommitFailureHandler.RolledBack(DbTransaction transaction, DbTransactionInterceptionContext interceptionContext)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbTransactionDispatcher.Dispose(DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.EntityClient.EntityTransaction.Dispose(Boolean disposing)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesToStore(SaveOptions options, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction)
   at System.Data.Entity.Infrastructure.DbExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectContext.SaveChangesInternal(SaveOptions options, Boolean executeInExistingTransaction)
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
...
```

It looks like there is some multi-threading bug in CommitFailureHandler.

### Further technical details
EF version: 6.4.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows Server 2019

DbConfiguration:
```
SetTransactionHandler(SqlProviderServices.ProviderInvariantName, () => new CommitFailureHandler());
SetExecutionStrategy(SqlProviderServices.ProviderInvariantName, () => new SqlAzureExecutionStrategy());
```

**Comment by dekenless** [comment]
I too experience the same exception under similar circumstances. I am using CommitFailureHandler & DbExecutionStrategy. 

I see is with SaveChanges, but also with stored procedure execution.

**Comment by moabba** [comment]
We're facing this issue as well. It started happening after we enabled MultipleActiveResultSets.

**Comment by EmoPlus** [comment]
This is affecting our production environment and is suspect of a memory leak.

**Comment by dekenless** [comment]
Any progress on resolving this?

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
