### ISSUE TITLE
Decimal conversion overflow for SQL Decimal 38,9 during Context.SaveChanges()

### ISSUE THREAD

**Issue by abbasnandwani** [dotnet/ef6#1647]
In SQL Server 2014 for a table column type is decimal (38,9) and in EF this is mapped to decimal. In OnModelCreating the property is setting precision using HasPrecision(38, 9). 

Problem is that EF6 is unable to save decimal value 99999999999999999999999999.123456 and this is valid .Net decimal value

When inserting using EF using context.SaveChanges() the result is "conversion overflows" exception message. 
```
Exception message: Inner Exception: {"Conversion overflows."}
Stack trace:
   at System.Data.SqlClient.TdsParser.TdsExecuteRPC(SqlCommand cmd, _SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<>c.<Reader>b__6_0(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Entity.Core.Mapping.Update.Internal.DynamicUpdateCommand.Execute(Dictionary`2 identifierValues, List`1 generatedValues)
   at System.Data.Entity.Core.Mapping.Update.Internal.UpdateTranslator.Update()
```
### Steps to reproduce

1. create a table tblTestDesc with one column as ID int PK and 2 columns Var1 and Var2 of type Decimal (28,9) and Decimal(38,9). 

1. Create EF model and then below code

1. Code below
```c#
using (var ctx = new Model2())
            {
                            
                ctx.Database.Log = Console.Write;

                var entity = new tblTestDec { Var1 = 1, Var2 = 99999999999999999999999999.123456M };

                ctx.tblTestDecs.Add(entity);
                ctx.SaveChanges();
            }
```

#### SQL generated by EF
```sql
INSERT [dbo].[tblTestDec]([Var1], [Var2])
VALUES (@0, @1)
SELECT [PKID]
FROM [dbo].[tblTestDec]
WHERE @@ROWCOUNT > 0 AND [PKID] = scope_identity()
-- @0: '1' (Type = Decimal, Precision = 28, Scale = 12)
-- @1: '99999999999999999999999999.12' (Type = Decimal, Precision = 38, Scale = 9)
-- Executing at 15/04/2020 10:47:45 +01:00
-- Failed in 268 ms with error: Conversion overflows.
```
### Further technical details
EF version: 6.4
Database Provider: EntityFramework.SqlServer
Operating system: Windows server 2014/Windows 10
IDE: Visual Studio 2015

**Comment by caimiss** [comment]
the same question with HasPrecision(36, 16), 
EF version: 6.4.4
Database Provider: EntityFramework.SqlServer
Operating system: Windows server 2014/Windows 10
IDE: Visual Studio 2017

INSERT [dbo].[ParameterEntities]([Type], [Compoperator], [ExpectedValue], [LowerLimit], [UpperLimit], [StrValue], [DecimalValue], [Name], [Description], [Result], [TestTime], [Units], [LogId])
VALUES (@0, @1, NULL, @2, @3, NULL, @4, @5, @6, @7, @8, @9, @10)
SELECT [Id]
FROM [dbo].[ParameterEntities]
WHERE @@ROWCOUNT > 0 AND [Id] = scope_identity()

-- @0: 'Numeric' (Type = String, Size = 50)
-- @1: 'GELE' (Type = String, Size = 128)
-- @2: '0.00001' (Type = Decimal, Precision = 36, Scale = 16)
-- @3: '0.0015' (Type = Decimal, Precision = 36, Scale = 16)
-- @4: '990000000000000000' (Type = Decimal, Precision = 36, Scale = 16)
-- @5: 'DC_ACC009' (Type = String, Size = 50)
-- @6: 'AC Common : DC Test : Current' (Type = String, Size = 255)
-- @7: 'Failed' (Type = String, Size = -1)
-- @8: '2019/12/14 18:20:28' (Type = DateTime2)
-- @9: 'A' (Type = String, Size = 50)
-- @10: '15' (Type = Int64)
-- Executing at 2020/6/30 12:57:51 +08:00
-- Failed in 0 ms with error: Conversion overflows.

Closed connection at 2020/6/30 12:57:51 +08:00



Exception thrown: 'System.Data.Entity.Infrastructure.DbUpdateException' in EntityFramework.dll

**Comment by icnocop** [comment]
As a work-around, I had to store the data as a string:

```
    public class MyEntity
    {
        public int Id { get; set; }

        public string MyDecimalStorage { get; set; }

        [NotMapped]
        public decimal MyDecimal
        {
            get
            {
                return Convert.ToDecimal(MyDecimalStorage);
            }
            set
            {
                MyDecimalStorage = value.ToString();
            }
        }
    }
```

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
