### ISSUE TITLE
Upgrading from 6.2.0 to 6.4.4 fails when using Shared App.config file.

### ISSUE THREAD

**Issue by domeister** [dotnet/ef6#1677]
When using Shared app.config file, the upgrade fails.
Upgrading a project with a non-shared app.config file succeeds.
```
Exception message:
Severity	Code	Description	Project	File	Line	Suppression State
Error		An error occurred while applying transformation to 'App.config' in project 'Tester' No element in the source document matches '/configuration/configSections/section[@name='entityFramework']'
No element in the source document matches '/configuration/configSections/section[@name='entityFramework']'				

Stack trace:
Attempting to gather dependency information for package 'EntityFramework.6.4.4' with respect to project 'Tester', targeting '.NETFramework,Version=v4.5.2'
Gathering dependency information took 149 ms
Attempting to resolve dependencies for package 'EntityFramework.6.4.4' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'EntityFramework.6.4.4'
Resolved actions to install package 'EntityFramework.6.4.4'
Removed package 'EntityFramework.6.2.0' from 'packages.config'
Successfully uninstalled 'EntityFramework.6.2.0' from Tester
Adding package 'EntityFramework.6.4.4' to folder 'D:\New Server Project - 2016\~In Progress Projects\BirdDog TalentUsers Service\packages'
Added package 'EntityFramework.6.4.4' to folder 'D:\New Server Project - 2016\~In Progress Projects\BirdDog TalentUsers Service\packages'
'App.config' already exists. Skipping...
Install failed. Rolling back...
Package 'EntityFramework.6.4.4' does not exist in project 'Tester'
Package 'EntityFramework.6.2.0' already exists in folder 'D:\New Server Project - 2016\~In Progress Projects\BirdDog TalentUsers Service\packages'
'App.config' already exists. Skipping...
Added package 'EntityFramework.6.2.0' to 'packages.config'
Executing script file 'D:\New Server Project - 2016\~In Progress Projects\BirdDog TalentUsers Service\packages\EntityFramework.6.2.0\tools\install.ps1'...

Type 'get-help EntityFramework' to see all available Entity Framework commands.
Removing package 'EntityFramework.6.4.4' from folder 'D:\New Server Project - 2016\~In Progress Projects\BirdDog TalentUsers Service\packages'
Removed package 'EntityFramework.6.4.4' from folder 'D:\New Server Project - 2016\~In Progress Projects\BirdDog TalentUsers Service\packages'
Executing nuget actions took 3.59 sec
System.IO.InvalidDataException: An error occurred while applying transformation to 'App.config' in project 'Tester' No element in the source document matches '/configuration/configSections/section[@name='entityFramework']' ---> Microsoft.Web.XmlTransform.XmlNodeException: No element in the source document matches '/configuration/configSections/section[@name='entityFramework']'
   at Microsoft.Web.XmlTransform.XmlTransformationLogger.LogErrorFromException(Exception ex)
   at Microsoft.Web.XmlTransform.XmlTransformation.Apply(XmlDocument xmlTarget)
   at NuGet.ProjectManagement.XdtTransformer.<PerformXdtTransformAsync>d__2.MoveNext()
   --- End of inner exception stack trace ---
   at NuGet.ProjectManagement.XdtTransformer.<PerformXdtTransformAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.ProjectManagement.XdtTransformer.<TransformFileAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.ProjectManagement.MSBuildNuGetProjectSystemUtility.<AddFilesAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.ProjectManagement.MSBuildNuGetProject.<InstallPackageAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteInstallAsync>d__85.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__76.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__75.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__74.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<>c__DisplayClass12_0.<<PerformActionImplAsync>b__0>d.MoveNext()
Time Elapsed: 00:00:03.7649465
========== Finished ==========


### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
Console.WriteLine("Hello World!");
```

### Further technical details
EF version: (found in project.csproj or packages.config)
Database Provider: (e.g. EntityFramework.SqlServer)
Operating system: (e.g. Windows 10) 
IDE: (e.g. Visual Studio 2017 15.6)

**Comment by tallalkazmi** [comment]
I am facing the exact same issue, any resolutions yet?

**Comment by ueberboss** [comment]
To work around the issue open the App.config file mentioned in the error. It will either look as follows or just be missing the "section" node with "name" attribute value "entityFramework".

`<?xml version="1.0" encoding="utf-8"?>
<configuration />`

Add the "entityFramework" section to the App.config as seen below

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
  </configSections>
</configuration>`

Then the upgrade should work.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by n1l** [comment]
For whose who could probably face the issue as well, I have a workaround that worked for me:
1. Copy App config data somewhere else
2. Delete app config from the project
3. Create new app config file and paste old app config file data
4. Change the entity framework section to:
`<section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />`

' requirePermission="false' is not realy needed but EF6 creates by default so I used it.
