### ISSUE TITLE
Upgrading to 6.4.4 from 6.2, CreateDatabaseIfNotExists initializer throws InvalidOperationException "The model has changed" despite no changes

### ISSUE THREAD

**Issue by grammophone** [dotnet/ef6#1689]
Hello,

We upgraded EF 6.2 to 6.4.4 on a Code First project with existing database and previous migrations. Initially, EF complained about the model being changed, and we issued an Add-Migration to see what it is. It was a no-operation, dropping and recreating indices defined with the new Core-style fluent API. After Update-Database, we issued again `Add-Migration -Name TestLeftovers` to see whether there are any more leftovers. The result was a blank migration, with no `Up` or `Down` content.

In any case, after any of the above migrations, the Update-Database reported "no pending migrations". But despite the migration tool reporting that everything is synchronized, the default initializer throws:

```
System.InvalidOperationException: The model backing the 'MyDbContext' context has changed since the database was created. Consider using Code First Migrations to update the database (http://go.microsoft.com/fwlink/?LinkId=238269).
   at System.Data.Entity.CreateDatabaseIfNotExists`1.InitializeDatabase(TContext context)
   at System.Data.Entity.Internal.InternalContext.<>c__DisplayClass66_0`1.<CreateInitializationAction>b__0()
   at System.Data.Entity.Internal.InternalContext.PerformInitializationAction(Action action)
   at System.Data.Entity.Internal.InternalContext.PerformDatabaseInitialization()
   at System.Data.Entity.Internal.LazyInternalContext.<>c.<InitializeDatabase>b__58_0(InternalContext c)
   at System.Data.Entity.Internal.RetryAction`1.PerformAction(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabaseAction(Action`1 action)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeDatabase()
   at System.Data.Entity.Internal.InternalContext.Initialize()
   at System.Data.Entity.Internal.InternalContext.ForceOSpaceLoadingForKnownEntityTypes()
   at System.Data.Entity.DbContext.System.Data.Entity.Infrastructure.IObjectContextAdapter.get_ObjectContext()
   at xxxx.DataAccess.EntityFramework.EFDomainContainer.WireEventHandlers() in C:\Projects\dotNet\Repositories\Solutions\xxxx\Components\xxxxx.DataAccess.EntityFramework\EFDomainContainer.cs:line 666
```
The last rows of the __MigrationHistory table are:
![image](https://user-images.githubusercontent.com/2425684/84553364-14d04000-ace2-11ea-807e-1b8a6daf9cef.png)

### Further technical details
EF version: 6.4.4
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.6.2)

Thank you.

**Comment by bakgaard** [comment]
Did you get anywhere with this?

**Comment by adammendoza** [comment]
Is there an upgrade guide?

**Comment by CZEMacLeod** [comment]
If you open the resx files for the last migration, and the 'leftovers' migration you will find a Target string entry.
Decode this as base64 then ungzip it to get the EDMX files for the model at each stage.
These are XML files which you can diff using your favourite tool to find out what the differences are from the code (`ConceptualModels`) perspective, even if there are no commands to execute to modify the materialized database schema (`StorageModels`).
Hopefully this will give you some starting point for working out why it thinks there are changes.
Remember that not all CodeFirst changes result in DB schema changes, but they may alter the model or mapping used.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
