### ISSUE TITLE
"The wait operation timed out." when running update-database, regardless of DbContext.CommandTimeout value

### ISSUE THREAD

**Issue by joelmdev** [dotnet/ef6#1728]
When running update-database, long running migrations fail with the following exception, regardless of CommandTimeout value:

```
Specify the '-Verbose' flag to view the SQL statements being applied to the target database.
Applying explicit migrations: [202003231649012_Foo].
Applying explicit migration: 202003231649012_Foo.
System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
The statement has been terminated. ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinTransaction(IEnumerable`1 migrationStatements, DbTransaction transaction, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinNewTransaction(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection)
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.<>c__DisplayClass2_0.<Execute>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements, DbTransaction existingTransaction)
   at System.Data.Entity.Migrations.DbMigrator.ExecuteOperations(String migrationId, VersionedModel targetModel, IEnumerable`1 operations, IEnumerable`1 systemOperations, Boolean downgrading, Boolean auto)
   at System.Data.Entity.Migrations.DbMigrator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.ApplyMigration(DbMigration migration, DbMigration lastMigration)
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.Infrastructure.MigratorLoggingDecorator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId)
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration)
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase)
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration)
   at System.Data.Entity.Infrastructure.Design.Executor.Update.<>c__DisplayClass0_0.<.ctor>b__0()
   at System.Data.Entity.Infrastructure.Design.Executor.OperationBase.Execute(Action action)
ClientConnectionId:5198b736-cf35-4614-9690-2c7f41df82d0
Error Number:-2,State:0,Class:11
Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
The statement has been terminated.
```

This is running against an Azure SQL database. 

### Steps to reproduce
Creating any long-running (but not as long as the CommandTimeout) migration seems to cause this, and this is not the first time we've run into this. Running update-database -script and running the resulting script through SSMS works fine, but this is not a real solution, especially for our CI pipeline.

### Further technical details
EF version: 6.4.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10

**Comment by jberent** [comment]
In my case the culprit is `RemoveRedundantDefaultDiscriminators(tableMapping);`  It takes **way** too long. It finds one 'Discriminator' to remove after searching for 6-10 minutes, (The table hierarchy doesn't even actually use a 'Discriminator' column).
I modified `System.Data.Entity.ModelConfiguration.Configuration.Mapping.EntityMappingService.Transform() to skip that call excpet when needed).  Now objectContext spins up in a couple of seconds...

**Comment by joelmdev** [comment]
@jberent Unfortunately we're not in a position where we can avoid all long running commands. From time to time we need to change the schema in a way that requires significant data reorganization to seed a new column, table, or combination of both by way of raw SQL. Those are typically the ones that cause the timeout, and there's not a good way for us to avoid them. Anytime we have one of these we catch it during a CI deployment to the dev environment and end up having to run the scripts manually against production in order to successfully migrate to the new schema.

**Comment by jberent** [comment]
Did you already try:
`
        private static int Main(string[] args)
        {
#if NET45 || NETCOREAPP
            System.Runtime.Remoting.Lifetime.LifetimeServices.LeaseTime = TimeSpan.FromMinutes(60);
            if (Console.IsOutputRedirected)
            {
                Console.OutputEncoding = Encoding.UTF8;
            }
#elif !NET40
`
That (`LeaseTime `) worked for me until I found the a way to shorten the Update-Database duration.  I couldn't find a way that didn't involve modifying the ef6 code itself.  Not ideal, but it is keeping us going....

**Comment by joelmdev** [comment]
@jberent thanks for the link. That's a pretty brutal workaround. I think our issue here is similar but different given the exception- not sure if this will fix it or not.

**Comment by joelmdev** [comment]
Could the ability to set this timeout be added to ef6.exe?

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by qbunia** [comment]
@joelmdev Ive set CommandTimeout in my DbMigrationsConfiguration. That helped me out to fix issue. More details:
https://learn.microsoft.com/en-us/dotnet/api/system.data.entity.migrations.dbmigrationsconfiguration.commandtimeout?view=entity-framework-6.2.0
