### ISSUE TITLE
Disabled test: Update_blocks_automatic_migration_when_explicit_source_model

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/ef6#1786]
I disabled the test as part of https://github.com/dotnet/ef6/pull/1780 to unblock dependency updates. Someone more familiar with the test should figure out the root cause and re-enabled the test.

Build: https://dev.azure.com/dnceng/public/_build/results?buildId=928383&view=results

Error:
```
Assert.Throws() Failure\r\nExpected: typeof(System.Data.Entity.Migrations.Infrastructure.AutomaticDataLossException)\r\nActual:   typeof(System.Data.SqlServerCe.SqlCeException): The specified table already exists. [ Orders ]\r\n---- System.Data.SqlServerCe.SqlCeException : The specified table already exists. [ Orders ]
   at System.Data.SqlServerCe.SqlCeCommand.ProcessResults(Int32 hr)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommandText(IntPtr& pCursor, Boolean& isBaseTableCursor)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommand(CommandBehavior behavior, String method, ResultSetOptions options)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteNonQuery()
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed) in /_/src/EntityFramework/Infrastructure/Interception/InternalDispatcher.cs:line 210
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext) in /_/src/EntityFramework/Infrastructure/Interception/DbCommandDispatcher.cs:line 56
   at System.Data.Entity.Migrations.DbMigrator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 1187
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 1082
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinTransaction(IEnumerable`1 migrationStatements, DbTransaction transaction, DbInterceptionContext interceptionContext) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 1132
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinNewTransaction(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 1152
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 1120
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 1057
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements, DbTransaction existingTransaction) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 1000
   at System.Data.Entity.Migrations.DbMigrator.ExecuteOperations(String migrationId, VersionedModel targetModel, IEnumerable`1 operations, IEnumerable`1 systemOperations, Boolean downgrading, Boolean auto) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 963
   at System.Data.Entity.Migrations.DbMigrator.AutoMigrate(String migrationId, VersionedModel sourceModel, VersionedModel targetModel, Boolean downgrading) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 885
   at System.Data.Entity.Migrations.DbMigrator.ApplyMigration(DbMigration migration, DbMigration lastMigration) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 759
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 580
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 535
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 1338
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 469
   at System.Data.Entity.Migrations.BasicMigrationScenarios.<>c__DisplayClass31_0.<Update_blocks_automatic_migration_when_explicit_source_model>b__0() in /_/test/FunctionalTests/Migrations/BasicMigrationScenarios.cs:line 616
----- Inner Stack Trace -----
   at System.Data.SqlServerCe.SqlCeCommand.ProcessResults(Int32 hr)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommandText(IntPtr& pCursor, Boolean& isBaseTableCursor)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommand(CommandBehavior behavior, String method, ResultSetOptions options)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteNonQuery()
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed) in /_/src/EntityFramework/Infrastructure/Interception/InternalDispatcher.cs:line 210
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.NonQuery(DbCommand command, DbCommandInterceptionContext interceptionContext) in /_/src/EntityFramework/Infrastructure/Interception/DbCommandDispatcher.cs:line 56
   at System.Data.Entity.Migrations.DbMigrator.ExecuteSql(MigrationStatement migrationStatement, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 1187
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbTransaction transaction, DbInterceptionContext interceptionContext) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 1082
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinTransaction(IEnumerable`1 migrationStatements, DbTransaction transaction, DbInterceptionContext interceptionContext) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 1132
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsWithinNewTransaction(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 1152
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection, DbInterceptionContext interceptionContext) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 1120
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatementsInternal(IEnumerable`1 migrationStatements, DbConnection connection) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 1057
   at System.Data.Entity.Migrations.DbMigrator.ExecuteStatements(IEnumerable`1 migrationStatements, DbTransaction existingTransaction) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 1000
   at System.Data.Entity.Migrations.DbMigrator.ExecuteOperations(String migrationId, VersionedModel targetModel, IEnumerable`1 operations, IEnumerable`1 systemOperations, Boolean downgrading, Boolean auto) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 963
   at System.Data.Entity.Migrations.DbMigrator.AutoMigrate(String migrationId, VersionedModel sourceModel, VersionedModel targetModel, Boolean downgrading) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 885
   at System.Data.Entity.Migrations.DbMigrator.ApplyMigration(DbMigration migration, DbMigration lastMigration) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 759
   at System.Data.Entity.Migrations.DbMigrator.Upgrade(IEnumerable`1 pendingMigrations, String targetMigrationId, String lastMigrationId) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 580
   at System.Data.Entity.Migrations.DbMigrator.UpdateInternal(String targetMigration) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 535
   at System.Data.Entity.Migrations.DbMigrator.EnsureDatabaseExists(Action mustSucceedToKeepDatabase) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 1338
   at System.Data.Entity.Migrations.DbMigrator.Update(String targetMigration) in /_/src/EntityFramework/Migrations/DbMigrator.cs:line 469
   at System.Data.Entity.Migrations.BasicMigrationScenarios.<>c__DisplayClass31_0.<Update_blocks_automatic_migration_when_explicit_source_model>b__0() in /_/test/FunctionalTests/Migrations/BasicMigrationScenarios.cs:line 616
```

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
