### ISSUE TITLE
EF6 is not getting custom factory by DbProviderFactories.GetFactory even I have set a factory by SetProviderFactory

### ISSUE THREAD

**Issue by mannok** [dotnet/ef6#1836]
Since I am developing a plugin for a software, the library (The one that I am developing) that uses EF6 won't be placed in the same directory as where the software located in. Therefore, I need to inject the factory instance instead of let EF6 find the provider automatically (Seems `DbProviderFactories.GetFactory()` finds the provider assembly only in the directory where the executable/startup program located in). However, seems it is not working as what I expected by calling `SetProviderFactory` and `SetProviderServices`. Any help would be appreciate. Thanks in advanced.

```
Exception message: Failed to find or load the registered .Net Framework Data Provider.
Stack trace: at System.Data.Common.DbProviderFactories.GetFactory(DataRow providerRow)
   at System.Data.Common.DbProviderFactories.GetFactory(String providerInvariantName)
   at PCCW.TD.TIS2.DAL.DbContexts.DbContext_PRD.TIS2APPContext.GetDefaultConnection() in C:\projects\pccw\tis2\cs\dTADVersion\PCCW.TD.TIS2.DAL\DBContexts\TIS2APP_PRD.TIS2APPContext.Generated.cs:line 50
   at PCCW.TD.TIS2.DAL.DbContexts.DbContext_PRD.TIS2APPContext..ctor() in C:\projects\pccw\tis2\cs\dTADVersion\PCCW.TD.TIS2.DAL\DBContexts\TIS2APP_PRD.TIS2APPContext.Generated.cs:line 44
   at dTAD_Version.dTAD_Tools_Toolbar.dTAD_Print.frm_printPDF.btn_batchExportTile_Click(Object sender, EventArgs e) in C:\projects\pccw\tis2\cs\dTADVersion\dTAD\dTAD Tools Toolbar\dTAD Print\frm_printPDF.cs:line 246
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

### Steps to reproduce
```c#
// Caller.cs
...

DbConfiguration.SetConfiguration(OracleConfiguration.Instance);

using (var ctx = new TIS2APPContext())
{
	var results = (
		from r in ctx.ACREGIONs
		select r
	).ToArray();
}

...
```

```c#
// OracleConfiguration.cs
public class OracleConfiguration : DbConfiguration
{
    public static readonly DbConfiguration Instance = new OracleConfiguration();

    private OracleConfiguration()
    {
        SetProviderFactory("Devart.Data.Oracle", OracleProviderFactory.Instance);
        SetProviderServices("Devart.Data.Oracle", OracleEntityProviderServices.Instance);
    }
}
```

```c#
// TIS2APPContext.cs
...

private static DbConnection GetDefaultConnection()
{
    DbProviderFactory factory = DbProviderFactories.GetFactory("Devart.Data.Oracle"); // <- THIS LINE THROWS ERROR!
    // DbProviderFactory factory = OracleProviderFactory.Instance; // <- If I use this line instead of above line, it works. Therefore, seems SetProviderFactory("Devart.Data.Oracle", OracleProviderFactory.Instance); is not working at all
    DbConnection connection = factory.CreateConnection();
    connection.ConnectionString = @"User Id=xxxxx;Password=yyyyyy;Server=zzzzzz;Persist Security Info=True";
    return connection;
}

...
```

### Further technical details
EF version: 6.4.4
Database Provider: Devart.Data.Oracle
Operating system: Windows 10
IDE: VS 2019

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
