### ISSUE TITLE
entity framework 6 migrations error

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1881]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/entity-framework-6-migrations-error/1477447)._

---
[severity:I'm unable to use this version] [regression] [worked-in:vsstudio2019]
ef 6 package manager console commands (Get-Migrations, Update-Database) do not work
the error is
System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.Data.Entity.Migrations.Extensions.ProjectExtensions.GetProjectTypes(Project project, Int32 shellVersion)
   at System.Data.Entity.Migrations.Extensions.ProjectExtensions.IsWebSiteProject(Project project)
   at System.Data.Entity.Migrations.Extensions.ProjectExtensions.GetTargetDir(Project project)
   at System.Data.Entity.Migrations.MigrationsDomainCommand.GetFacade(String configurationTypeName, Boolean useContextWorkingDirectory)
   at System.Data.Entity.Migrations.UpdateDatabaseCommand.<>c__DisplayClass2. <.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
Value cannot be null.
Parameter name: type
PM>

---
#### Feedback Bot on 7/19/2021, 08:07 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by MMR16** [comment]
I have the same problem on visual studio 2022 Version 17.0.0 Preview 4.1 
when enable-migrations ,
so I install visual studio 2019 & worked well 
hope to fix the problem on final release.

**Comment by ajcvickers** [comment]
@MMR16 Make sure you are using the latest version of EF6. That is, [EF 6.4.4](https://www.nuget.org/packages/EntityFramework/6.4.4). Earlier versions do not work with Visual Studio 17.

**Comment by MikeDPeterson** [comment]
@ajcvickers Is it possible that earlier versions of EF (ex: EF 6.1.3 ) will work in future versions of VS2022?

**Comment by ajcvickers** [comment]
@MikeDPeterson No. If something isn't working, the only way we have to fix it is to release a new version.

**Comment by MikeDPeterson** [comment]
@ajcvickers OK, that is what I figured :).  One more question. Is the issue limited to Package Manager Console commands? In other words, if we aren't doing any migration operations, will VS2022 be ok to use?

**Comment by ajcvickers** [comment]
I believe so.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
