### ISSUE TITLE
Relationship between an entity using TPC with a parent and a child class and another class throws an exception

### ISSUE THREAD

**Issue by Lawlzee** [dotnet/ef6#1895]
EF6 throws an exception while creating the EF model when there is a one to many relationship between:
- An entity with a parent and one or more child classes, using the TPC inheritance strategy
- A normal entity

Exception:
```
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Data.Entity.ModelConfiguration.Configuration.Mapping.ForeignKeyPrimitiveOperations.<>c__DisplayClass12_0.<RemoveAllForeignKeyConstraintsForColumn>b__1(ForeignKeyBuilder fk)
   at System.Data.Entity.Utilities.IEnumerableExtensions.Each[T](IEnumerable`1 ts, Action`1 action)
   at System.Data.Entity.ModelConfiguration.Configuration.Mapping.EntityMappingConfiguration.CleanupUnmappedArtifacts(DbDatabaseMapping databaseMapping, EntityType table)
   at System.Data.Entity.ModelConfiguration.Configuration.Mapping.EntityMappingConfiguration.Configure(DbDatabaseMapping databaseMapping, ICollection`1 entitySets, DbProviderManifest providerManifest, EntityType entityType, EntityTypeMapping& entityTypeMapping, Boolean isMappingAnyInheritedProperty, Int32 configurationIndex, Int32 configurationCount, IDictionary`2 commonAnnotations)
   at System.Data.Entity.ModelConfiguration.Configuration.Types.EntityTypeConfiguration.ConfigureTablesAndConditions(EntityTypeMapping entityTypeMapping, DbDatabaseMapping databaseMapping, ICollection`1 entitySets, DbProviderManifest providerManifest)
   at System.Data.Entity.ModelConfiguration.Configuration.ModelConfiguration.ConfigureEntityTypes(DbDatabaseMapping databaseMapping, ICollection`1 entitySets, DbProviderManifest providerManifest)
   at System.Data.Entity.ModelConfiguration.Configuration.ModelConfiguration.Configure(DbDatabaseMapping databaseMapping, DbProviderManifest providerManifest)
   at System.Data.Entity.DbModelBuilder.Build(DbProviderManifest providerManifest, DbProviderInfo providerInfo)
   at System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection)
   at System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
   at System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.LazyInternalContext.get_ModelBeingInitialized()
   at System.Data.Entity.Infrastructure.EdmxWriter.WriteEdmx(DbContext context, XmlWriter writer)
   at System.Data.Entity.Utilities.DbContextExtensions.GetModel(Action`1 writeXml)
   at System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationsConfiguration configuration, DbContext usersContext, DatabaseExistenceState existenceState, Boolean calledByCreateDatabase)
   at System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationsConfiguration configuration)
   at System.Data.Entity.Migrations.Design.MigrationScaffolder..ctor(DbMigrationsConfiguration migrationsConfiguration)
   at System.Data.Entity.Infrastructure.Design.Executor.CreateMigrationScaffolder(DbMigrationsConfiguration configuration)
   at System.Data.Entity.Infrastructure.Design.Executor.ScaffoldInternal(String name, DbConnectionInfo connectionInfo, String migrationsConfigurationName, Boolean ignoreChanges)
   at System.Data.Entity.Infrastructure.Design.Executor.Scaffold.<>c__DisplayClass0_0.<.ctor>b__0()
   at System.Data.Entity.Infrastructure.Design.Executor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
   at System.Data.Entity.Infrastructure.Design.Executor.OperationBase.Execute(Action action)
```

### Steps to reproduce
Create a model with these entities and DbContext:

```
namespace TPCBug
{
    public class TopClass
    {
        public Guid Id { get; set; }
    }

    public class MiddleClass : TopClass
    {
        public OtherClass OtherClass { get; set; }
        public Guid? OtherClass_FK { get; set; }
    }

    public class BottomClass : MiddleClass
    {

    }

    public class OtherClass
    {
        public Guid Id {  get; set; }
        public List<MiddleClass> MiddleClasses { get; set; }
    }

    public class MyDbContext : DbContext
    {
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TopClass>()
                .Map(x =>
                {
                    x.MapInheritedProperties();
                    x.ToTable("TopClass");
                });
            modelBuilder.Entity<MiddleClass>()
                .Map(x =>
                {
                    x.MapInheritedProperties();
                    x.ToTable("MiddleClass");
                });
            modelBuilder.Entity<BottomClass>()
                .Map(x =>
                {
                    x.MapInheritedProperties();
                    x.ToTable("BottomClass");
                });
            modelBuilder.Entity<OtherClass>()
                .Map(x =>
                {
                    x.MapInheritedProperties();
                    x.ToTable("OtherClass");
                });

            modelBuilder.Entity<MiddleClass>()
                .HasOptional(x => x.OtherClass)
                .WithMany(x => x.MiddleClasses)
                .HasForeignKey(x => x.OtherClass_FK);
        }
    }
}
```
Run `Enable-Migrations`, `Add-Migration` or instantiate `MyDbContext`.

### Further technical details
EF version: 6.4.4
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10)
IDE: Visual Studio 2022 preview 3.1

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
