### ISSUE TITLE
I can't use EF 6 commands on the package manager console

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1897]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/I-cant-use-EF-6-commands-on-the-package/1525038)._

---
All EF6 commands fails because a loading issue, I believe this is because that console is now running 64 bits code, but there is no option to revert it to 32 bits powershell mode so commands won't work. This is problematic because EF commands are an integral part of dev cycle and I need to go back and forth 2019 for this specific task.
Thanks!

PM> update-database
Exception calling "CreateInstance" with "7" argument(s): "Could not load file or assembly 'EnvDTE, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. El sistema no puede encontrar el archivo especificado."
At C:\Repositorios\ProactiveMgmt\LSPediaGIT\packages\EntityFramework.6.2.0\tools\EntityFramework.psm1:783 char:5
+     $dispatcher = $utilityAssembly.CreateInstance(
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : FileNotFoundException
 
System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.Data.Entity.Migrations.Extensions.ProjectExtensions.GetProjectTypes(Project project, Int32 shellVersion)
   at System.Data.Entity.Migrations.Extensions.ProjectExtensions.IsWebSiteProject(Project project)
   at System.Data.Entity.Migrations.Extensions.ProjectExtensions.GetTargetDir(Project project)
   at System.Data.Entity.Migrations.MigrationsDomainCommand.GetFacade(String configurationTypeName, Boolean useContextWorkingDirectory)
   at System.Data.Entity.Migrations.UpdateDatabaseCommand.<>c__DisplayClass2. <.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
Value cannot be null.
Parameter name: type

---
#### Feedback Bot on 9/9/2021, 04:25 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
@dotnet/efteam @bricelam We probably need to do something here.

**Comment by bricelam** [comment]
Try again using EF 6.3 or 6.4. Older versions seem to get more incompatible with each release of VS.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
