### ISSUE TITLE
Is AlwaysEncrypted support in EF6 for .Net Core?

### ISSUE THREAD

**Issue by dekenless** [dotnet/ef6#1909]
When attempting to add "Column Encryption Setting=Enabled" connection string, the following error occurs:

```
Exception message: Keyword not supported: 'column encryption setting'.
Stack trace:
   at System.Data.Entity.Core.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString)
   at System.Data.Entity.Core.EntityClient.EntityConnection..ctor(String connectionString)
   at System.Data.Entity.Internal.LazyInternalConnection.InitializeFromConnectionStringSetting(ConnectionStringSettings appConfigConnection)
   at System.Data.Entity.Internal.LazyInternalConnection.TryInitializeFromAppConfig(String name, AppConfig config)
   at System.Data.Entity.Internal.LazyInternalConnection.Initialize()
   at System.Data.Entity.Internal.LazyInternalConnection.CreateObjectContextFromConnectionModel()
   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.InternalContext.Initialize()
   at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
   at System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
   at System.Data.Entity.Internal.Linq.InternalSet`1.ActOnSet(Action action, EntityState newState, Object entity, String methodName)
   at System.Data.Entity.Internal.Linq.InternalSet`1.Add(Object entity)
   at System.Data.Entity.DbSet`1.Add(TEntity entity)

```

### Further technical details
EF version: 6.4.4
Database Provider:  EntityFramework.SqlServer
Operating system: . Windows 10
IDE:  Visual Studio 2019 16.11.4

**Comment by ErikEJ** [comment]
Sorry, missed ":NET Core" in the title - the .NET Core version of System.Data.SqlClient does not support always encrypted.This is basically a duplicate of #823 which also contains a solution.

**Comment by dekenless** [comment]
> Sorry, missed ":NET Core" in the title - the .NET Core version of System.Data.SqlClient does not support always encrypted.This is basically a duplicate of #823 which also contains a solution.

Ah, thanks. I had a look at the ErikEJ.EntityFramework.SqlServer package and in my tests it seems to work with code first, but I haven't had any luck getting it to work with a EDMX.

**Comment by ErikEJ** [comment]
For runtime, see the linked issue and solution. For design time, I doubt there will be a solution any time soon.
