### ISSUE TITLE
Error With Update-Database Command FROM VS2022 Preview

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/ef6#1918]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Error-With-Update-Database-Command-FROM-/1582419)._

---
[severity:I'm unable to use this version] [regression]
System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.Data.Entity.Migrations.Extensions.ProjectExtensions.GetProjectTypes(Project project, Int32 shellVersion)
   at System.Data.Entity.Migrations.Extensions.ProjectExtensions.IsWebSiteProject(Project project)
   at System.Data.Entity.Migrations.Extensions.ProjectExtensions.GetTargetDir(Project project)
   at System.Data.Entity.Migrations.MigrationsDomainCommand.GetFacade(String configurationTypeName, Boolean useContextWorkingDirectory)
   at System.Data.Entity.Migrations.UpdateDatabaseCommand.<>c__DisplayClass2. <.ctor>b__0()
   at System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)
Value cannot be null.
Parameter name: type

Product Description

Microsoft Visual Studio Professional 2022 (64-bit) - Preview
Version 17.1.0 Preview 1.0
Microsoft .Net
Version 4.8.04161

Version: 4.8

---
#### Feedback Bot on 11/15/2021, 07:40 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Pierrick Fidon on 11/15/2021, 03:23 PM: 

<p>I have the same problem on 2022 (17.0.0) and it works fine on version 16.11.5</p>
<p>PM&gt; Add-Migration PF_20211115_1550<br>
System.ArgumentNullException: La valeur ne peut pas être null.<br>
Nom du paramètre : type<br>
à System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)<br>
à System.Activator.CreateInstance(Type type, Object[] args)<br>
à System.Data.Entity.Migrations.Extensions.ProjectExtensions.GetProjectTypes(Project project, Int32 shellVersion)<br>
à System.Data.Entity.Migrations.Extensions.ProjectExtensions.IsWebSiteProject(Project project)<br>
à System.Data.Entity.Migrations.Extensions.ProjectExtensions.GetTargetDir(Project project)<br>
à System.Data.Entity.Migrations.MigrationsDomainCommand.GetFacade(String configurationTypeName, Boolean useContextWorkingDirectory)<br>
à System.Data.Entity.Migrations.AddMigrationCommand.Execute(String name, Boolean force, Boolean ignoreChanges)<br>
à System.Data.Entity.Migrations.MigrationsDomainCommand.Execute(Action command)<br>
La valeur ne peut pas être null.<br>
Nom du paramètre : type<br>
PM&gt;</p>

---
### Original Solutions
(no solutions)

**Comment by ajcvickers** [comment]
EF 6.2 doesn't work. You will need to update to EF 6.4.4. We have so far been unable to reproduce this with EF 6.4.4. If you are seeing this with EF 6.4.4, then please attach a small, runnable project or post a small, runnable code listing that reproduces what you are seeing so that we can investigate.

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
