### ISSUE TITLE
The 'Context.Database.SqlQuery(...)' does not work with the ColumnAttibute

### ISSUE THREAD

**Issue by monze** [dotnet/ef6#1932]
I don't know if this is a bug, or just me trying to used EF in a way, it was not intended - so please help my.

I'm tying to extract data, but the desired search is dynamic created based on user input. To support this, I have found no other way but to manually create the SQL, and use the demoContext.Database.SqlQuery<>(..)  method, to extract the data - which work fine in my first test.

But, the DbModel that should be used, is created with one naming convention for the C# class and another naming convention for the table column. This is illustrated below.

```
    [Table("Test")]
    public class TestDbModel
    {
        [Column("id", Order = 0)]
        [Key]
        public Guid Id { get; set; }

        [Column("databaseNamingConvention", Order = 1)]
        [Required]
        public string CSharpNamingConvention { get; set; }
    }
```

This works fine, when using the DbSet<TestDbMode> to add, remove, and retrieve data.

But when I try to use the xxContext.Database.SqlQuery<>(..) as below it fails.

```
    using (DemoContext context = new DemoContext())
    {
        IList<TestDbModel> list = context
            .Database
            .SqlQuery<TestDbModel>("SELECT * FROM [dbo].[Test]")
            .ToList();
    }
```

Exception message:
The data reader is incompatible with the specified 'Company.Product.DbModel.TestDbModel'. A member of the type, 'CSharpNamingConvention', does not have a corresponding column in the data reader with the same name.

Stack trace:

```
   at System.Data.Entity.Core.Query.InternalTrees.ColumnMapFactory.GetMemberOrdinalFromReader(DbDataReader storeDataReader, EdmMember member, EdmType currentType, Dictionary`2 renameList)
   at System.Data.Entity.Core.Query.InternalTrees.ColumnMapFactory.GetColumnMapsForType(DbDataReader storeDataReader, EdmType edmType, Dictionary`2 renameList)
   at System.Data.Entity.Core.Query.InternalTrees.ColumnMapFactory.CreateColumnMapFromReaderAndType(DbDataReader storeDataReader, EdmType edmType, EntitySet entitySet, Dictionary`2 renameList)
   at System.Data.Entity.Core.Objects.ObjectContext.InternalTranslate[TElement](DbDataReader reader, String entitySetName, MergeOption mergeOption, Boolean streaming, EntitySet& entitySet, TypeUsage& edmType)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteStoreQueryInternal[TElement](String commandText, String entitySetName, ExecutionOptions executionOptions, Object[] parameters)
   at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass186_0`1.<ExecuteStoreQueryReliably>b__1()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectContext.<>c__DisplayClass186_0`1.<ExecuteStoreQueryReliably>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteStoreQueryReliably[TElement](String commandText, String entitySetName, ExecutionOptions executionOptions, Object[] parameters)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteStoreQuery[TElement](String commandText, ExecutionOptions executionOptions, Object[] parameters)
   at System.Data.Entity.Internal.InternalContext.<>c__DisplayClass111_0`1.<ExecuteSqlQuery>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

If I change the SQL so the extracted column match the properties in the model, everything works.

```
    using (DemoContext context = new DemoContext())
    {
        IList<TestDbModel> list = context
            .Database
            .SqlQuery<TestDbModel>(
              @"SELECT [id] AS [Id],
                       [databaseNamingConvention] AS CSharpNamingConvention
                  FROM [dbo].[Test]")
            .ToList();
    }
```

So it seems, that when using the demoContext.Database.SqlQuery<>(..), the 'ColumnAttribute' is not used in in the column/property matching.

### Steps to reproduce
Open the attached solution, and run the program. It will create a Demo database, add one table, and try to used is.
It shows both when it fails and when it works.

### Further technical details
EF version:  6.4.4
Database Provider: invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer"
Operating system: Windows 10
IDE: Microsoft Visual Studio Community 2019
[Demo.zip](https://github.com/dotnet/ef6/files/7777671/Demo.zip)

Jacob Mogensen, Denmark

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
