### ISSUE TITLE
Using Access Token to Connect to Sql Server in Entity Framework

### ISSUE THREAD

**Issue by tshoham** [dotnet/ef6#1965]
We are moving to connecting to our sql server with an access token instead of a connection string. Previously, we had in the connection string a property "metadata" which referenced the compiled model files (csdl, ssdl, msl) that entity framework needs (using EF6- 6.4.0).

Once we moved to providing the access token, we tried to leave in the connection string the server url and the db name, along with keeping the metadata property as we had previously. However, now we are getting an exception that metadata is not a recognized property.

How can use an access token to connect to the database, while still providing the needed entity framework model files?

Old Constructor:
`public CustomDbContext(string connectionString): base($"metadata=res://*/Db.CustomDataModel.csdl|res://*/Db.CustomDataModel.ssdl|res://*/Db.CustomDataModel.msl;provider=System.Data.SqlClient;provider connection string='{connectionString}'")
{ }`

New Constructor:
`public CustomDbContext(string token) : base("metadata=res://*/Db.CustomDataModel.csdl|res://*/Db.CustomDataModel.ssdl|res://*/Db.CustomDataModel.msl;server=tcp<server>.database.windows.net;database=<db>")
{ 
    var conn = (System.Data.SqlClient.SqlConnection)Database.Connection;
    conn.AccessToken = token;
}`

```
Exception:
`System.ArgumentException: Keyword not supported: 'metadata'.
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms)
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.<>c.<SetConnectionString>b__8_0(DbConnection t, DbConnectionPropertyInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.SetConnectionString(DbConnection connection, DbConnectionPropertyInterceptionContext`1 interceptionContext)
   at System.Data.Entity.Infrastructure.SqlConnectionFactory.CreateConnection(String nameOrConnectionString)
   at System.Data.Entity.Infrastructure.LocalDbConnectionFactory.CreateConnection(String nameOrConnectionString)
   at System.Data.Entity.Internal.LazyInternalConnection.Initialize()
   at System.Data.Entity.Internal.LazyInternalConnection.get_Connection()
   at System.Data.Entity.Internal.LazyInternalContext.get_Connection()
   at System.Data.Entity.Database.get_Connection()

### Further technical details
EF version: EF6 (6.4.0)
Database Provider: SqlServer
Operating system: Managed by Azure
IDE:  Visual Studio 2019

**Comment by ErikEJ** [comment]
If you use Azure AD to obtain the token  you can use my alternative EF6 provider that allows you to specify how to get the token via the connection string. No interceptor required. 

https://www.nuget.org/packages/ErikEJ.EntityFramework.SqlServer/

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
