### ISSUE TITLE
LINQ query compilation regression for left outer join

### ISSUE THREAD

**Issue by madelson** [dotnet/ef6#1975]
After updating from EF 6.3.0 to EF 6.4.4, one of our LINQ queries that previously worked now fails to compile with the following exception:

```
	System.Data.Entity.Core.EntityCommandCompilationException: An error occurred while preparing the command definition. See the inner exception for details.
 ---> System.NotSupportedException: The query attempted to call 'OuterApply' over a nested query, but 'OuterApply' did not have the appropriate keys.
   at System.Data.Entity.Core.Query.PlanCompiler.NestPullup.ApplyOpJoinOp(Op op, Node n)
   at System.Data.Entity.Core.Query.PlanCompiler.NestPullup.VisitApplyOp(ApplyBaseOp op, Node n)
   at System.Data.Entity.Core.Query.InternalTrees.BasicOpVisitorOfT`1.Visit(OuterApplyOp op, Node n)
   at System.Data.Entity.Core.Query.InternalTrees.OuterApplyOp.Accept[TResultType](BasicOpVisitorOfT`1 v, Node n)
   at System.Data.Entity.Core.Query.InternalTrees.BasicOpVisitorOfNode.VisitChildren(Node n)
   at System.Data.Entity.Core.Query.PlanCompiler.NestPullup.Visit(ProjectOp op, Node n)
   at System.Data.Entity.Core.Query.InternalTrees.BasicOpVisitorOfNode.VisitChildren(Node n)
   at System.Data.Entity.Core.Query.PlanCompiler.NestPullup.Visit(ProjectOp op, Node n)
   at System.Data.Entity.Core.Query.InternalTrees.BasicOpVisitorOfNode.VisitChildren(Node n)
   at System.Data.Entity.Core.Query.PlanCompiler.NestPullup.Visit(PhysicalProjectOp op, Node n)
   at System.Data.Entity.Core.Query.InternalTrees.PhysicalProjectOp.Accept[TResultType](BasicOpVisitorOfT`1 v, Node n)
   at System.Data.Entity.Core.Query.PlanCompiler.NestPullup.Process()
   at System.Data.Entity.Core.Query.PlanCompiler.PlanCompiler.Compile(List`1& providerCommands, ColumnMap& resultColumnMap, Int32& columnCount, Set`1& entitySets)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition..ctor(DbProviderFactory storeProviderFactory, DbCommandTree commandTree, DbInterceptionContext interceptionContext, IDbDependencyResolver resolver, BridgeDataReaderFactory bridgeDataReaderFactory, ColumnMapFactory columnMapFactory)
   --- End of inner exception stack trace ---
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition..ctor(DbProviderFactory storeProviderFactory, DbCommandTree commandTree, DbInterceptionContext interceptionContext, IDbDependencyResolver resolver, BridgeDataReaderFactory bridgeDataReaderFactory, ColumnMapFactory columnMapFactory)
   at System.Data.Entity.Core.EntityClient.Internal.EntityProviderServices.CreateCommandDefinition(DbProviderFactory storeProviderFactory, DbCommandTree commandTree, DbInterceptionContext interceptionContext, IDbDependencyResolver resolver)
   at System.Data.Entity.Core.EntityClient.Internal.EntityProviderServices.CreateDbCommandDefinition(DbProviderManifest providerManifest, DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Common.DbProviderServices.CreateCommandDefinition(DbCommandTree commandTree, DbInterceptionContext interceptionContext)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.CreateCommandDefinition(ObjectContext context, DbQueryCommandTree tree)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlanFactory.Prepare(ObjectContext context, DbQueryCommandTree tree, Type elementType, MergeOption mergeOption, Boolean streaming, Span span, IEnumerable`1 compiledQueryParameters, AliasGenerator aliasGenerator)
   at System.Data.Entity.Core.Objects.ELinq.ELinqQueryState.GetExecutionPlan(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery.ToTraceString()
   at System.Data.Entity.Internal.Linq.InternalQuery`1.ToTraceString()
   at System.Data.Entity.Infrastructure.DbQuery`1.ToString()
   at UserQuery.Main() in ...
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
void Main()
{
	var cs = new SqlConnectionStringBuilder { DataSource = @".\sqlexpress", IntegratedSecurity = true }.ConnectionString;
	using var context = new MyContext(cs);
	using var t = context.Database.BeginTransaction();
	
	var q = from e1 in context.E1s
			join e2 in context.E2s on e1.Id equals e2.Value into gj
			from innerItem in gj.DefaultIfEmpty()
			select e1.Id;

	Console.WriteLine(q.ToString());
}

public class MyContext : DbContext
{
	public MyContext(string connectionString) : base(connectionString) { }
	
	public DbSet<E1> E1s {get; set;}
	public DbSet<E2> E2s {get; set;}
}

[Table("e1")]
public class E1 {
	[Key]
	public int Id {get; set;}
}

[Table("e2")]
public class E2
{
	[Key, Column(Order = 1), DatabaseGenerated(DatabaseGeneratedOption.None)]
	public int Id { get; set; }
	[Key, Column(Order = 2)]
	public int Value {get; set;}
}
```

In EF 6.3.0, this prints the following instead of failing:
```SQL
SELECT
    [Extent1].[Id] AS [Id]
    FROM  [dbo].[e1] AS [Extent1]
    LEFT OUTER JOIN [dbo].[e2] AS [Extent2] ON [Extent1].[Id] = [Extent2].[Value]
```

### Further technical details
EF version: 6.4.4
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2022

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
