### ISSUE TITLE
Getting Target Invocation Exception while updating .edmx file - Sql server approch

### ISSUE THREAD

**Issue by shailesh1984** [dotnet/ef6#1976]
Exception message:
Stack trace: 
Error in Log file :
28-03-2022 16:44:21
Recoverable
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: The "Compile" rule is missing the "AutoGen" property.
   at Microsoft.Verify.Operation(Boolean condition, String unformattedMessage, Object arg1, Object arg2)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.DynamicTypeBrowseObject.<<VSLangProj-FileProperties-get_IsCustomToolOutput>b__38_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously[T](Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.DynamicTypeBrowseObject.VSLangProj.FileProperties.get_IsCustomToolOutput()
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.DynamicTypeBrowseObject.VSLangProj80.FileProperties2.get_IsCustomToolOutput()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAPropertyInfo.get_Value()
   at Microsoft.VisualStudio.Modeling.Shell.SubordinateFileHelper.GetChildProjectItemIds(IVsHierarchy parentHierarchy, UInt32 parentItemId)
   at Microsoft.VisualStudio.Modeling.Shell.SubordinateFileHelper.GetChildProjectItemFileNames(IVsHierarchy parentHierarchy, UInt32 parentItemId)
   at Microsoft.VisualStudio.Modeling.Shell.DocData.QuerySaveFile(String fileName, tagVSQuerySaveFlags querySaveFlags)
   at Microsoft.VisualStudio.Modeling.Shell.DocData.SaveDocData(VSSAVEFLAGS flags, String& fileName, Int32& saveCanceled)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass685_0.<<SaveItem>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass571_0.<<HrMutate>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously[T](Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass568_0.<HrInvoke>b__0()
   at Microsoft.VisualStudio.ProjectSystem.VS.HResult.Invoke(Func`1 action, IServiceProvider vsShellServiceProvider, IProjectFaultHandlerService projectFaultHandlerService, UnconfiguredProject project)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>g__action|0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )

![image](https://user-images.githubusercontent.com/6926778/160393566-094bd553-f5af-4c67-bed4-fb118e306f3c.png)

![image](https://user-images.githubusercontent.com/6926778/160394188-4f34d925-9f75-4d93-813b-40ba6e5a22a3.png)

### Further technical details
Framework Version: 4.7.2
EF version: (found in project.csproj or packages.config)
Database Provider: (e.g. EntityFramework.SqlServer)
Operating system: (e.g. Windows 10) 
IDE: (e.g. Visual Studio 2017 15.6)

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by shailesh1984** [comment]
@ajcvickers Thank you

**Comment by matherm-aboehm** [comment]
@shailesh1984  I had exactly the same issue and found a workaround for this:

Place a custom XAML Rule definition file for `Compile` item types next to a `Directoy.Build.targets` file or project file where the `.edmx` was included.
I combined both predefined files from Visual Studio into a single file, see this [gist](https://gist.github.com/matherm-aboehm/97d14dedfa41eeca6c38a4663391acb1).
Then add the following into the `Directoy.Build.targets` or project file:

```html
  <!-- Common Project System rules that override rules defined in msbuild. These are exact copy of the rules defined in msbuild. -->
  <ItemGroup Condition="'$(DefineCommonManagedItemSchemas)' == 'true'">
    <!-- Combines Rule definition file Compile.xaml and Compile.BrowseObject.xaml,
    to fix bug in new project system (CPS) for SDK styled projects.
    see: https://github.com/dotnet/ef6/issues/1976 -->
    <PropertyPageSchema Include="$(MSBuildThisFileDirectory)Compile.xaml">
      <Context>File;BrowseObject</Context>
    </PropertyPageSchema>
  </ItemGroup>
``` 
See [docs](https://github.com/microsoft/VSProjectSystem/blob/master/doc/extensibility/adding_xaml_rules.md) for more info on this matter.
