### ISSUE TITLE
Thread.CurrentThread.CurrentCulture settings are leaked into the generated SQL causing invalid SQL

### ISSUE THREAD

**Issue by osjoberg** [dotnet/ef6#2205]
I understand that EF6 is no longer actively manitained, however this is an issue that occurs under .NET8 while the same version of EF6 (6.4.4) works as I expect under .NET Framework 4.8. 

Migrating from .NET Framework 4.8 to .NET8 while keeping EF6 will certainly make our migration easier since we do not need to change a core component of our system so that we can do it in smaller steps. I hope you consider fixing this issue as I believe other project may be in the same situation.

### Code

```sql
CREATE TABLE Test (TestId INT NOT NULL)
```
```csharp
using System.Data.Entity;
using System.Globalization;

// This is what causes the issue, sets CultureInfo.Numberformat.NegativeSign 
// to '−' (code point 8722) instead of the SQL negative sign '-' (code point 45).
Thread.CurrentThread.CurrentCulture = new CultureInfo("sv-SE");

var context = new TestDbContext("Server=127.0.0.1; Database=TestDatabase; User Id=TestUser; Password=TestPassword;");

// Exception thrown here.
context.Tests.FirstOrDefault(test => test.TestId == -1);

public class TestDbContext : DbContext
{
    public TestDbContext(string nameOrConnectionString) : base(nameOrConnectionString)
    {
    }

    public IDbSet<Test> Tests { get; set; }
}

public class Test
{
    public int TestId { get; set; }
}
```

### Exception
```
System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while executing the command definition. See the inner exception for details.
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass41_0.<GetResults>b__1()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass41_0.<GetResults>b__0()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__31_0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<>c__14`1.<GetElementFunction>b__14_1(IEnumerable`1 sequence)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   at Program.<Main>$(String[] args) in D:\Temp\ConsoleApp2\ConsoleApp2\Program.cs:line 12
```
Inner exception
```
System.Data.SqlClient.SqlException: Incorrect syntax near '−'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.<>c.<Reader>b__6_0(DbCommand t, DbCommandInterceptionContext`1 c)
   at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
   at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext)
   at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
```
### Provider and version information

EF version: 6.4.4
Database provider: Microsoft SQL Server provider
Target framework: .NET8
Operating system: Windows 10
IDE: Visual Studio 2022 (64-bit) 17.8.6

**Comment by ErikEJ** [comment]
what happens if you do not use a constant?

**Comment by osjoberg** [comment]
It will work as EF will parameterize the SQL query. If nothing else, it is a work-around that can be used.

**Comment by ErikEJ** [comment]
@osjoberg Cool, do not expect any bug fixes to EF6!

**Comment by osjoberg** [comment]
I see that this has been reported before so I guess it will not be fixed. 

If anyone have any insight onto why the behaviour differs between .NET Framework 4.8 and .NET8 I would be interested to know. 

Are there any other issues that can arise from having Thread.CurrentThread.CurrentCulture set?

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.

**Comment by CZEMacLeod** [comment]
@osjoberg My understanding is that `CurrentCulture` will affect the SQL generated in both net48 and net8, and it should be set to match the locale of your SQL server.
This can also affect your persistence data when serializing/deserializing.
You can use `CurrentCultureUI` for formatting strings etc. for your end user to differentiate between the two.

**Comment by osjoberg** [comment]
@CZEMacLeod Im pretty sure this is an error only EF6/.NET7 as this error was found when porting a large system from .NET Framework 4.8 to .NET7.  I have created two different console applications with the repro above one for .NET Framework 4.8 and one for .NET7. where the .NET Framework console application works, the .NET7 version throws an exception while trying to execute the invalid SQL.

I belive it is correct of my system to set  `CurrentCulture` to present curerncies, dates etc. in a localized fashion. In this legacy system it has had no other side effect until now.
