### ISSUE TITLE
Wrong detection for "The entity types 'Xxx' and 'Yyy' cannot share table 'Ttt' because they are not in the same type hierarchy or do not have a valid one to one foreign key relationship with matching primary keys between them."

### ISSUE THREAD

**Issue by cincuranet** [dotnet/ef6#583]
When the model is built, entity can be wrongly included in mapping of other, although it's actually mapped to another table.

```
Exception message: System.InvalidOperationException: The entity types 'DocumentSet' and 'Document' cannot share table 'DocumentSet' because they are not in the same type hierarchy or do not have a valid one to one foreign key relationship with matching primary keys between them.
Stack trace:
at System.Data.Entity.ModelConfiguration.Configuration.Mapping.EntityMappingConfiguration.UpdateColumnNamesForTableSharing(DbDatabaseMapping databaseMapping, EntityType entityType, EntityType toTable, MappingFragment fragment)
   at System.Data.Entity.ModelConfiguration.Configuration.Mapping.EntityMappingConfiguration.FindOrCreateTargetTable(DbDatabaseMapping databaseMapping, MappingFragment fragment, EntityType entityType, EntityType fromTable, Boolean& isTableSharing)
   at System.Data.Entity.ModelConfiguration.Configuration.Mapping.EntityMappingConfiguration.Configure(DbDatabaseMapping databaseMapping, ICollection`1 entitySets, DbProviderManifest providerManifest, EntityType entityType, EntityTypeMapping& entityTypeMapping, Boolean isMappingAnyInheritedProperty, Int32 configurationIndex, Int32 configurationCount, IDictionary`2 commonAnnotations)
   at System.Data.Entity.ModelConfiguration.Configuration.Types.EntityTypeConfiguration.ConfigureTablesAndConditions(EntityTypeMapping entityTypeMapping, DbDatabaseMapping databaseMapping, ICollection`1 entitySets, DbProviderManifest providerManifest)
   at System.Data.Entity.ModelConfiguration.Configuration.ModelConfiguration.ConfigureEntityTypes(DbDatabaseMapping databaseMapping, ICollection`1 entitySets, DbProviderManifest providerManifest)
   at System.Data.Entity.ModelConfiguration.Configuration.ModelConfiguration.Configure(DbDatabaseMapping databaseMapping, DbProviderManifest providerManifest)
   at System.Data.Entity.DbModelBuilder.Build(DbProviderManifest providerManifest, DbProviderInfo providerInfo)
   at System.Data.Entity.DbModelBuilder.Build(DbConnection providerConnection)
   at System.Data.Entity.Internal.LazyInternalContext.CreateModel(LazyInternalContext internalContext)
   at System.Data.Entity.Internal.RetryLazy`2.GetValue(TInput input)
   at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
   at System.Data.Entity.Internal.InternalContext.Initialize()
   at System.Data.Entity.Internal.InternalContext.ForceOSpaceLoadingForKnownEntityTypes()
   at System.Data.Entity.DbContext.System.Data.Entity.Infrastructure.IObjectContextAdapter.get_ObjectContext()
```

### Steps to reproduce
The code below produces the exception, although both `Document` and `DocumentSet` are properly mapped. The problem is from [here](https://github.com/aspnet/EntityFramework6/blob/master/src/EntityFramework/ModelConfiguration/Configuration/Mapping/EntityMappingConfiguration.cs#L741) where when the `DocumentSet` entity is configured, it finds `Document` entity (already mapped to `DocumentSet` table) as "related" and tries to do the initial mapping.

Workaround for now could be to rename the `DocumentSet` to i.e. `DocumentSetX`, hence the above mentioned matching is not happening.

```c#
class Program
{
	static void Main(string[] args)
	{
		Database.SetInitializer<MyContext>(null);
		using (var ctx = new MyContext())
		{
			Console.WriteLine((ctx as IObjectContextAdapter).ObjectContext.CreateDatabaseScript());
		}
	}
}

class Document
{
	public int Id { get; set; }
}

class DocumentSet
{
	public int Id { get; set; }
}

class MyContext : DbContext
{
	public DbSet<Document> DocumentSet { get; set; }
	public DbSet<DocumentSet> DocumentSetSet { get; set; }

	protected override void OnModelCreating(DbModelBuilder modelBuilder)
	{
		base.OnModelCreating(modelBuilder);
		modelBuilder.Configurations.Add(new DocumentConfiguration());
		modelBuilder.Configurations.Add(new DocumentSetConfiguration());
	}
}

class DocumentConfiguration : EntityTypeConfiguration<Document>
{
	public DocumentConfiguration()
	{
		ToTable("DocumentSet");
	}
}

class DocumentSetConfiguration : EntityTypeConfiguration<DocumentSet>
{
	public DocumentSetConfiguration()
	{
		ToTable("FooSet");
	}
}
```

### Further technical details
EF version: 6.2.0
Database Provider: agnostic, EntityFramework.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.7

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
