### ISSUE TITLE
Flakey test: Cannot open database "SimpleModel.EmptyContext"

### ISSUE THREAD

**Issue by bricelam** [dotnet/ef6#770]
Got a CI failure in FunctionalTests:

```  ProductivityApiTests.DatabaseInitializationTests.DropCreateDatabaseIfModelChanges_recreates_database_if_database_exists_and_model_does_not_match [FAIL]
      System.Data.Entity.Core.EntityException : The underlying provider failed on Open.
      ---- System.Data.SqlClient.SqlException : Cannot open database "SimpleModel.EmptyContext" requested by the login. The login failed.
      Login failed for user 'b0002O8\vsagent'.
      Stack Trace:
        /_/src/EntityFramework/Core/EntityClient/EntityConnection.cs(588,0): at System.Data.Entity.Core.EntityClient.EntityConnection.Open()
        /_/src/EntityFramework/Core/Objects/ObjectContext.cs(1661,0): at System.Data.Entity.Core.Objects.ObjectContext.EnsureConnection(Boolean shouldMonitorTransactions)
        /_/src/EntityFramework/Core/Objects/ObjectContext.cs(3248,0): at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
        /_/src/EntityFramework/Core/Objects/ObjectQuery`.cs(700,0): at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass41_0.<GetResults>b__0()
        /_/src/EntityFramework/Core/Objects/ObjectQuery`.cs(699,0): at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
        /_/src/EntityFramework/Core/Objects/ObjectQuery`.cs(568,0): at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__31_0()
        /_/src/EntityFramework/Internal/LazyEnumerator`.cs(54,0): at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
           at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
        /_/test/EntityFramework/FunctionalTests/ProductivityApi/DatabaseInitializationTests.cs(485,0): at ProductivityApiTests.DatabaseInitializationTests.get_CompressedEmptyModel()
        /_/test/EntityFramework/FunctionalTests/ProductivityApi/DatabaseInitializationTests.cs(497,0): at ProductivityApiTests.DatabaseInitializationTests.MutateMigrationsHistory(DbConnection connection)
        /_/test/EntityFramework/FunctionalTests/ProductivityApi/DatabaseInitializationTests.cs(752,0): at ProductivityApiTests.DatabaseInitializationTests.DropCreateDatabaseIfModelChanges_recreates_database_if_database_exists_and_model_does_not_match()
        ----- Inner Stack Trace -----
           at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
           at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
           at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
           at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
           at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
           at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
           at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
           at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
           at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
           at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
           at System.Data.SqlClient.SqlConnection.Open()
        /_/src/EntityFramework/Infrastructure/Interception/InternalDispatcher.cs(138,0): at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext](TTarget target, Action`2 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed)
        /_/src/EntityFramework/Infrastructure/Interception/DbConnectionDispatcher.cs(286,0): at System.Data.Entity.Infrastructure.Interception.DbConnectionDispatcher.Open(DbConnection connection, DbInterceptionContext interceptionContext)
        /_/src/EntityFramework/Core/EntityClient/EntityConnection.cs(577,0): at System.Data.Entity.Core.EntityClient.EntityConnection.Open()
```

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
