### ISSUE TITLE
DbExecutionStrategy doesn't catch SqlException caused by a deadlock

### ISSUE THREAD

**Issue by pheinz1974** [dotnet/ef6#872]
Until EF 6.1.3 I could either use the SqlAzureStrategy or write my own DbExecutionStrategy to handle SqlExceptions such as the classical deadlock error:
> Transaction (Process ID 58) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

Overriding DbExecutionStrategy .ShouldRetryOn(Exception exception) and returning true in case of SqlException provoked the EF to rerun the  failed Transaction.

In EF 6.2.0 the method DbExecutionStrategy.ShouldRetryOn(Exception exception) is not executed anymore when the database reports a deadlock situation. Instead the SqlException is passed directly to the caller.

Here is my DbExecutionStrategy:
```c#
    internal class StorageServiceExecutionStrategy : DbExecutionStrategy
    {
        public StorageServiceExecutionStrategy(int iMaxRetryCount, TimeSpan tsMaxRetryDelay)
            : base(iMaxRetryCount, tsMaxRetryDelay)
        {
        }

        protected override bool ShouldRetryOn(Exception exception)
        {
            // find exception with retry condition
            while (exception != null)
            {
                // check retry condition
                bool bShouldRetry = exception is TimeoutException
                                 || exception is SqlException;

                if (bShouldRetry)
                {
                    try
                    {
                        // write windows EventLog entry
                        string strMessage = string.Format("Exception while access the database try to retry, message {0}", exception.Message);
                        EventLog.WriteEntry("Storage Service", strMessage, EventLogEntryType.Error);
                    }
                    catch { }

                    return true;
                }

                // navigate to next level
                exception = exception.InnerException;
            }

            // no retry condition found
            return false;
        }
    }
```

### Further technical details
EF version: 6.2.0
Database Provider: EntityFramework.SqlServer
Operating system: Windows 10 
IDE: Visual Studio 2017

**Comment by ste-camp** [comment]
I'm having the same issue of deadlock not being retried on EF 6.4.4
It works perfectly on timeouts (SqlServer Error -2) and connection lost exceptions (Sql Server Error 10054), but `ShouldRetryOn()` is not called at all for deadlocks (Sql Server Error 1205)

This is my ExecutionStrategy class:
```C#
public class AWSDbStrategy: DbExecutionStrategy
    {
        public AWSDbStrategy(): this(5, TimeSpan.FromSeconds(30))
        {
        }

        public AWSDbStrategy(int maxRetryCount, TimeSpan maxDelay): base(maxRetryCount, maxDelay)
        {
        }

        protected override bool ShouldRetryOn(Exception exception)
        {   
            var deadlocked = IsAnyInnerExceptionWithErrno(exception, 1205);
            
            var timedout = IsAnyInnerExceptionWithErrno(exception, -2); //Riprova le query in timeout
            
            var loginTransient = IsAnyInnerExceptionWithErrno(exception, 10054); 


            return deadlocked || timedout || loginTransient;
        }

        private bool IsAnyInnerExceptionWithErrno(Exception e, int errorNumber)
        {
            if (e is SqlException sqle && sqle.Number == errorNumber)
            {
                return true;
            }

            if (e.InnerException != null)
            {
                return IsAnyInnerExceptionWithErrno(e.InnerException, errorNumber);
            }

            return false;
        }
    }
```

The exception I get is:

```
System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while reading from the store provider's data reader. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Transaction (Process ID 104) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

System.Data.SqlClient.SqlException (0x80131904): Transaction (Process ID 104) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at System.Data.Entity.Core.Common.Internal.Materialization.Shaper`1.StoreRead()
ClientConnectionId:eba29793-739b-4655-af4a-608ae306b149
Error Number:1205,State:51,Class:13
```

**Comment by ajcvickers** [comment]
This issue has been closed because EF6 is no longer being actively developed. We are instead focusing on stability of the codebase, which means we will only make changes to address security issues. See the repo [README](https://github.com/dotnet/ef6/blob/main/README.md) for more information.
